# puthi-cicd-templates/.github/actions/setup-php-laravel/action.yml
name: setup-php-laravel
description: "Set up Laravel for CI"
inputs:
  mode:
    description: "fast or full"
    required: true
runs:
  using: "composite"
  steps:
    - uses: shivammathur/setup-php@v2
      with: { php-version: '8.2' }

    - run: composer install --no-interaction --no-progress
      shell: bash

    - if: ${{ inputs.mode == 'fast' }}
      run: php artisan test --testsuite=Unit
      shell: bash

    - if: ${{ inputs.mode == 'full' }}
      run: |
        php artisan test
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        tar -czf $RUNNER_TEMP/app.tgz \
          --exclude-vcs --exclude='.github' --exclude='storage' --exclude='.env' .
        echo "PACKAGE_PATH=$RUNNER_TEMP/app.tgz" >> $GITHUB_ENV
      shell: bash
